### ISSUE TITLE
Prep project boards for Migration

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/revenue#36]
### Overview
We need to prepare the Project Boards for the forced migration that GitHub is doing in August, so that it is already working well for the team by then.

### Action Items
- [x]  copy this template to a comment below
   ````
   ### Text from project board card, [Add name of column here]
   ```
   [INSERT MARKDOWN HERE]
   ```
   - [ ] Determine where this item goes on the wiki (page and section)
   - [ ] copy item to wiki
   - [ ] hide this comment when completed.
   ````
- [x] copy markdown from a card in the "Start Here" column of the Project Board into your new comment where it says `[INSERT MARKDOWN HERE]
- [x] delete card from project board.

### Resources/Instructions
Classic Project board URL(s): 
  - https://github.com/hackforla/revenue/projects/3
  - https://github.com/hackforla/revenue/projects/1
  
New Project board URL(s):
  - https://github.com/orgs/hackforla/projects/58

**Comment by ExperimentsInHonesty** [comment]
### Text from previous Revenue (Fundraising & Earned) Open Roles project board card, Instructions
```
# START HERE
We know this board is ugly!!!

- [Find a volunteer Opportunity](https://github.com/hackforla/revenue/projects/2#card-53874331)
- [Post a volunteer Opportunity](https://github.com/hackforla/revenue/projects/2#card-53874327)
- [Remove a volunteer Opportunity](https://github.com/hackforla/revenue/projects/2#card-53874321)

If you know some places where we should post these opportunities please [submit Fundraising channels](https://docs.google.com/forms/d/e/1FAIpQLSfWfrfEdeuWCundCLLP0HA-cOrDzgZsfxkTazDafqG0b0MYCg/viewform) after you check to make sure its not on the list of  [existing Fundraising channels we know about](https://docs.google.com/spreadsheets/d/1Q1YyP_8sSBFBSfzEN66MS6TvJ6PR2HtmpnhfCk7sKpE/preview)
```
This links to other cards, which have been copied below.
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Earned Revenue, Links/Questions/Review
```
Project One Sheets:
- [Completed One Sheets](https://github.com/hackforla/product-management/tree/master/project-one-sheets)
- [Issue for tracking updates](https://github.com/hackforla/product-management/issues/3)
```
- [x] same as a comment below
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Earned Revenue, Links/Questions/Review
```
[Youth Justice Nav Project proposal](https://github.com/hackforla/YouthJusticeNav/issues/28)
```
- [x] Determine where this item goes on the wiki (page and section) - added issue to the [CoP: Fundraising: Project Board: YJN tab](https://github.com/orgs/hackforla/projects/112/views/5)
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Fundraising, Start Here
```
We meet at 1pm PST /4pm EST.  
```
- [ ] This is no longer true
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Fundraising, Start Here
```
[Funders by SDG](https://sdgfunders.org/sdgs/goal/peace-and-justice/dataset/recent/location/United%20States/)
```
- [x] Created a new issue https://github.com/hackforla/revenue/issues/37
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Fundraising, Ice Box
```
Letter head template
```
- [ ] created an issue https://github.com/hackforla/revenue/issues/40
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Fundraising, Links/Questions/Review
```
[Hack for LA deck](https://docs.google.com/presentation/d/12YxUxDE3yCSws4k6XxRjBqKN36K8QHGuH--QYiqs6rM/edit#slide=id.gc6e5a81019_1_0)
```
- [x] Determine where this item goes on the wiki (page and section) - https://github.com/hackforla/revenue/wiki
- [x] copy item to wiki
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Fundraising, Links/Questions/Review
```
Grant Programs
- [AWS $100K](https://aws.amazon.com/government-education/nonprofits/aws-imagine-grant-program/)
```
- [x] already in an issue https://github.com/hackforla/revenue/issues/11
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Fundraising, Links/Questions/Review
```
Platform we are considering
#### CivicCRM
- https://github.com/civicrm/civicrm-wordpress
- https://github.com/civicrm
```
- [x] Moved to https://github.com/hackforla/revenue/issues/39
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Fundraising, Links/Questions/Review
```
Other related Boards
[Governance](https://github.com/hackforla/governance/projects/2)
```
- [x] No longer relevant, we moved the 2 issues related to revenue to https://github.com/hackforla/revenue
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Fundraising, Links/Questions/Review
```
### Links
- [Fundraising Google Drive](https://drive.google.com/drive/folders/1hjYu8EGHfmGTdNTVLxMChZ-apc6zr4_U?usp=sharing)

#### Project One Sheets:
- [Completed One Sheets](https://github.com/hackforla/product-management/tree/master/project-one-sheets)
- [Issue for tracking updates](https://github.com/hackforla/product-management/issues/3)
```
- [x] Determine where this item goes on the wiki (page and section) - https://github.com/hackforla/revenue/wiki
- [x] copy item to wiki
- [x] hide this comment when completed.

**Comment by Rabia2219** [comment]
#### Notes

- [x] make issues for 
  - https://github.com/hackforla/revenue/issues/36#issuecomment-2270056612
  - ~https://github.com/hackforla/revenue/issues/36#issuecomment-2270058783~  - already in an issue https://github.com/hackforla/revenue/issues/11
- [x] create wiki page and add
  - https://github.com/hackforla/revenue/issues/36#issuecomment-2270058088
  - https://github.com/hackforla/revenue/issues/36#issuecomment-2270061580
